### ISSUE TITLE
Problems building godot with this module

### ISSUE THREAD

**Issue by fenix-hub** [wowtomi/godot-mysql-module#6]
Hi, Im trying to compile godot 3.0 on windows with this module.
The building stops with this message:
'reference.h' no such file or directory
What can I do?

**Comment by zenogears** [comment]
scons: Reading SConscript files ...
Enabling ALSA
Enabling PulseAudio
Checking for C header file mntent.h... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
[Initial build] Compiling ==> modules/mysql/mysql.cpp
In file included from modules/mysql/mysql.cpp:10:0:
modules/mysql/mysql.h:10:10: fatal error: reference.h: No such file or directory
 #include "reference.h"
          ^~~~~~~~~~~~~
compilation terminated.
scons: *** [modules/mysql/mysql.linuxbsd.tools.64.o] Error 1
scons: building terminated because of errors.

:(
